import type { InbreedingFactor } from "./types.ts";

type FactorSet = readonly InbreedingFactor[];

export const ANCESTOR_FACTORS: Record<string, FactorSet> = {
  "A.P. Indy": ["stamina", "sustain"],
  "Almahmoud": ["speed", "acceleration"],
  "Alzao": ["acceleration"],
  "Alydar": ["power", "guts"],
  "Blushing Groom": ["speed", "sustain"],
  "Bold Ruler": ["speed", "power"],
  "Buckpasser": ["guts", "power"],
  "Busted": ["sustain"],
  "Caro": ["stamina", "power"],
  "Cosmah": ["sustain"],
  "Danehill": ["speed", "power"],
  "Danzig": ["speed", "power"],
  "Deep Impact": ["speed", "acceleration"],
  "Fappiano": ["power", "sustain"],
  "Galileo": ["stamina", "sustain"],
  "Hail to Reason": ["guts", "acceleration"],
  "Halo": ["speed", "fear"],
  "Highclere": ["stamina"],
  "King Kamehameha": ["speed", "power"],
  "Kingmambo": ["speed", "acceleration"],
  "Kris S.": ["stamina", "guts"],
  "Lady Victoria": ["guts"],
  "Lyphard": ["speed"],
  "Mill Reef": ["stamina", "sustain"],
  "Mr. Prospector": ["speed", "power", "acceleration"],
  "Native Dancer": ["speed", "power"],
  "Nijinsky": ["stamina", "acceleration"],
  "Northern Dancer": ["speed", "stamina", "power"],
  "Northern Taste": ["stamina", "guts"],
  "Nureyev": ["speed", "acceleration"],
  "Princely Gift": ["speed"],
  "Raise a Native": ["speed", "power"],
  "Roberto": ["stamina", "guts"],
  "Sadler's Wells": ["stamina", "sustain"],
  "Sakura Bakushin O": ["speed"],
  "Sakura Hagoromo": ["guts"],
  "Sakura Yutaka O": ["speed"],
  "Sea-Bird": ["stamina", "sustain"],
  "Seattle Slew": ["speed", "guts"],
  "Secretariat": ["stamina", "sustain"],
  "Sir Ivor": ["acceleration"],
  "Storm Bird": ["speed", "power"],
  "Storm Cat": ["speed", "power"],
  "Sugar Heart": ["fear"],
  "Sunday Silence": ["speed", "guts", "acceleration"],
  "Tesco Boy": ["speed"],
  "Turn-to": ["guts"],
  "Victoria Park": ["speed"],
  "What a Pleasure": ["sustain"],
  "Wind in Her Hair": ["stamina", "acceleration"],
};

export function getAncestorFactors(name: string): InbreedingFactor[] {
  return [...(ANCESTOR_FACTORS[name] ?? [])];
}
